name: GithubActoinsTest
on: [push]

jobs:
  first_job:
    name: Initial Job
    runs-on: ubuntu-latest
    steps:
      - name: Github First Step
        uses: actions/checkout@master
      - run: echo All Done!
      - run: echo Test Artifact > test.txt
      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: test.txt
